<template>
  <transition name="walletTran">
    <div class="wallet-wrap">
      <ul >
        <li class="wallet scale-up-center"  @click.stop="detail">
          <span>钱包1</span>
          <span>{{coinData ? coinData.address : ''}}</span>
          <i class="fa fa-times remove" aria-hidden="true"  @click.stop="remove"></i>
        </li>
      </ul>
    </div>  
  </transition>
</template>
<script>
export default {
  props: {
    createWallet: '1',
    coinData: {
      default: ''
    }
  },
  data() {
    return {
      show: false
    }
  },
  methods: {
    remove() {
      console.log('remove');
    },
    detail() {
      this.$router.push({path: 'walletDetail', query: {address: this.coinData.BTC? this.coinData.BTC.address : ''}});
    }
  },
  created() {
    this.show = true;
  }
}
</script>
<style lang="scss" scoped>
.wallet-wrap {
  opacity: 1;
  &.walletTran-enter-active {
    -webkit-animation: scale-up-center 3s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    animation: scale-up-center 3s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    opacity: 1;
  }
  // &.walletTran-enter {
  //   opacity: 0;
  // }
}

.wallet-wrap {
  position: absolute;
  top: 70px;
  left: 90px;
  .wallet {
    position: relative;
    width: 200px;
    height: 70px;
    background: yellowgreen;
    background: #fff;
    box-shadow: 0 1px 3px rgba(0,0,0,.3);
    border-radius: 2px;
    box-sizing: border-box;
    list-style: none;
    & > span {
      font-size: 20px;
      padding: 10px;
     color: #606266;

    }
    & > .remove {
      position: absolute;
      right: 7px;
      top: 5px;
    }
    
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2018-9-26 17:45:50
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

</style>
